# Generated by Django 5.1.4 on 2026-05-12 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "order",
                    models.PositiveIntegerField(unique=True, verbose_name="Порядок"),
                ),
                (
                    "icon_url",
                    models.CharField(blank=True, max_length=500, verbose_name="Иконка"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Тема",
                "verbose_name_plural": "Темы",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Название")),
                ("order", models.PositiveIntegerField(verbose_name="Порядок в теме")),
                (
                    "lesson_type",
                    models.CharField(
                        choices=[
                            ("theory", "Теория"),
                            ("practice", "Практика"),
                            ("test", "Тест"),
                        ],
                        max_length=20,
                        verbose_name="Тип урока",
                    ),
                ),
                ("content", models.JSONField(default=dict, verbose_name="Контент")),
                (
                    "starter_code",
                    models.TextField(blank=True, verbose_name="Стартовый код"),
                ),
                (
                    "test_cases",
                    models.JSONField(default=list, verbose_name="Тест-кейсы"),
                ),
                (
                    "xp_reward",
                    models.PositiveIntegerField(default=10, verbose_name="Награда XP"),
                ),
                (
                    "stars_reward",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Награда звёзды"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "theme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="lessons.theme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
                "ordering": ["theme", "order"],
                "unique_together": {("theme", "order")},
            },
        ),
        migrations.CreateModel(
            name="UserProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "completed",
                    models.BooleanField(default=False, verbose_name="Завершён"),
                ),
                (
                    "stars_earned",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Звёзды"),
                ),
                (
                    "attempts",
                    models.PositiveIntegerField(default=0, verbose_name="Попытки"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Завершён в"
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to="lessons.lesson",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Прогресс пользователя",
                "verbose_name_plural": "Прогресс пользователей",
                "unique_together": {("user", "lesson")},
            },
        ),
    ]
