# Generated by Django 5.1.4 on 2026-05-24 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertaskgeneration",
            name="last_generated_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Последняя генерация"
            ),
        ),
    ]
